### PR TITLE
retained is now a system keyword, fixes compiler issue

### PR DESCRIPTION
**Pull request by technobly**
This just released in v0.4.6 https://docs.particle.io/reference/firmware/photon/#backup-ram

### CODE REVIEW

**Comment by kri5** [comment]
Is there something preventing this to be merged?

**Comment by technobly** [comment]
@kri5 it just takes a human touch from @hirotakaster who is the owner of this library, but it should merge right in and then can be re-imported in the Particle Libraries ;-)

**Comment by hirotakaster** [comment]
okay, I will check this now.

**Comment by hirotakaster** [comment]
@kri5 @technobly thank you!! I merge this, and re-import to Particle libraries.

**Comment by technobly** [comment]
Thanks @hirotakaster!

**Pull request merged**
